### ISSUE TITLE
Port to GNOME 47

### ISSUE THREAD

**Issue by antrmn** [fthx/bottom-overview#1]
GNOME 47.rc has been released, with the stable release set for September 18. Please update for GNOME 47 compatibility. The upgrade guide can be found here: [Port Extensions to GNOME Shell 47](https://gjs.guide/extensions/upgrading/gnome-shell-47.html)

Thanks!

**Comment by fthx** [comment]
https://github.com/fthx/bottom-overview/commit/2ad31c289fb13eba220673efad17eaf094b72e48

Please reopen if this does not work with GS 47.
Since it seems there are few changes, I do not plan to make a GS 47 VM and I do run GS 46.

It's uploaded to web ext so you should get an update soon.
